### Comprobar que la API vive
GET http://localhost:3000/

####################
##  REPARACIONES  ##
####################

### 1. Obtener todas las reparaciones (GET)
GET http://localhost:3000/api/reparaciones

### 2. Crear una nueva reparación (POST)
POST http://localhost:3000/api/reparaciones
Content-Type: application/json

{
  "fecha": "2026-03-30T10:00:00Z",
  "descripcion": "Cambio de aceite",
  "taller_nombre": "Talleres Pedro",
  "kilometraje_momento": 226000,
  "vehiculoMatricula": "1234BBB"
}

### 3. Actualizar una reparación (PUT)
PUT http://localhost:3000/api/reparaciones/22
Content-Type: application/json

{
  "kilometraje_momento": 110000,
  "descripcion": "Cambio de pastillas, aceite y filtros nuevos"
}

### 4. Eliminar una reparación (DELETE)
DELETE http://localhost:3000/api/reparaciones/31

### 5. Buscar el historial de un coche por matrícula (GET)
GET http://localhost:3000/api/reparaciones/vehiculo/1234CCC

####################
##  PRESUPUESTOS  ##
####################

### 1. Ver todos los presupuestos con su reparación (GET)
GET http://localhost:3000/api/presupuestos

### 2. Crear un presupuesto automatizado (POST)
POST http://localhost:3000/api/presupuestos
Content-Type: application/json

{
  "base_imponible": 400.00,
  "reparacionId": 29
}

### 3. Actualizar un presupuesto (PUT)
PUT http://localhost:3000/api/presupuestos/9
Content-Type: application/json

{
  "base_imponible": 300.00
}

### 4. Eliminar un presupuesto (DELETE)
DELETE http://localhost:3000/api/presupuestos/12

### 5. Subir PDF a un presupuesto (Multipart Form)
### Debemos crear un presupuesto asignado a una reparacion, cambiamos el id
### y en la base de datos se comprueba que la url_pdf ha cambiado
POST http://localhost:3000/api/presupuestos/16/pdf
Content-Type: multipart/form-data; boundary=MiLimiteDeArchivo

--MiLimiteDeArchivo
Content-Disposition: form-data; name="archivo"; filename="prueba.pdf"
Content-Type: application/pdf

< holiwisssssssssssssss
--MiLimiteDeArchivo--

####################
##  COMPARADOR IA  ##
####################

### 1. Analizar Presupuesto con Inteligencia Artificial (GET)
GET http://localhost:3000/api/comparador/16/analizar