### 1. Comprobar que la API vive
GET http://localhost:3000/

### 2. Obtener todas las reparaciones (GET)
GET http://localhost:3000/api/reparaciones

### 3. Crear una nueva reparación (POST)
POST http://localhost:3000/api/reparaciones
Content-Type: application/json

{
  "fecha": "2026-03-30T10:00:00Z",
  "descripcion": "Cambio de pastillas de freno y aceite",
  "taller_nombre": "Talleres Paco",
  "kilometraje_momento": 144000,
  "vehiculoMatricula": "1234 CDD"
}

### 4. Crear un presupuesto asociado a la reparación 1 (POST)
POST http://localhost:3000/api/presupuestos
Content-Type: application/json

{
  "importe_total": 182.10,
  "base_imponible": 150.50,
  "IVA": 31.60,
  "reparacionId": 21
}

### 5. Ver todos los presupuestos con su reparación (GET)
GET http://localhost:3000/api/presupuestos